{
 "title": "Android性能测试",
 "time": { "from": "2023-01-30T01:04:55.726Z", "to": "2023-01-30T01:10:23.764Z" },
 "panels": [
  {
   "title": "冷启动时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(leng_ThisTime) AS leng_ThisTime,\n  avg(leng_TotalTime) AS leng_TotalTime,\n  avg(leng_WaitTime) AS leng_WaitTime\nFROM test.and_qidtime\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time)\n"
    }
   ]
  },
  {
   "title": "热启动时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(ThisTime) AS ThisTime,\n  avg(TotalTime) AS TotalTime,\n  avg(WaitTime) AS WaitTime\nFROM test.and_qidtime\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time) \n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(cpu) AS cpu\nFROM test.and_cpu\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time)\n"
    }
   ]
  },
  {
   "title": "内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(total) AS total,\n  avg(heap_free) AS heap_free\nFROM test.and_meminfo\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time)\n"
    }
   ]
  },
  {
   "title": "流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(time) AS time,\r\n  avg(down_net) AS down_net,\r\n  avg(up_net) AS up_net,\r\n  avg(total_down) AS total_down,\r\n  avg(total_up) AS total_up\r\nFROM test.and_wlan\r\nWHERE unix_timestamp(time)\r\nGROUP BY 1\r\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  },
  {
   "title": "电量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(power) AS power\n FROM test.and_power\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time) \n"
    }
   ]
  }
 ]
}