{
 "title": "IOS应用性能测试",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(time) AS time,\r\n  avg(memory) AS memory\r\nFROM test.my_memory\r\nWHERE unix_timestamp(time)\r\nGROUP BY 1\r\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(fps) AS fps,\n  avg(jank) AS jank,\n  avg(big_jank) AS big_jank,\n   avg(stutter) AS stutter\nFROM test.my_fps\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time)\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(time) AS time,\r\n  avg(use_cpu) AS use_cpu,\r\n  avg(sys_cpu) AS sys_cpu,\r\n  avg(count_cpu) AS count_cpu\r\nFROM test.my_cpu\r\nWHERE unix_timestamp(time)\r\nGROUP BY 1\r\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS time,\n  avg(gpu_Device) AS gpu_Device,\n  avg(gpu_Renderer) AS gpu_Renderer,\n  avg(gpu_Tiler) AS gpu_Tiler\nFROM test.my_gpu\nWHERE unix_timestamp(time)\nGROUP BY 1\nORDER BY UNIX_TIMESTAMP(time)\n"
    }
   ]
  }
 ]
}